### ISSUE TITLE
bad request error in replit but not if you copy the link and go to it.

### ISSUE THREAD

**Issue by astaugaard** [FCS-Coding-Club/FCS-ClubHub#11]
# this error if you submit the form in replit
Bad Request
The CSRF session token is missing.

# works fine when it is not embedded in the page
ie copy from the top part of the view and paste in the search bar.

**Comment by SeanMcGoff** [comment]
That's a security feature I added so that an attacker can't preform a [CSRF attack](https://owasp.org/www-community/attacks/csrf#:~:text=Cross%2DSite%20Request%20Forgery%20). This shouldn't happen if you open the web view in a new tab
<img width="741" alt="Screen Shot 2021-12-07 at 8 54 30 AM" src="https://user-images.githubusercontent.com/44823666/145041901-10574528-e0cb-4cca-90ba-e38c309052f5.png">
